runtime: go113
handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /favicon.svg
  static_files: favicon.svg
  upload: favicon.svg
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: auto
env_variables:
  COMMIT: dev
  LASTMOD: dev
main: src/regexplanet.go